Arm
Troy-Argonauts/2023RobotCode pull request #20
Opened 2023-02-22 20:44 UTC by SolidityContract

Added Arm Subsystem

2023-02-22 22:50 UTC, kelmalon requested changes
Please reach out with any questions

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/Constants.java
>      }
REMOVE manipulator interface from this branch

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +     * Enums are the states of the intake rollers.
What are the states? List them in javadoc

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +     * @param state desired state of intake rollers (FORWARD, OFF, BACKWARD) to a motor speed
Remove list of states from parameter

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +     * @param speed sets elbow motor to desired speed given that it is within the encoder limits
"desired motor speed"

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +     * @param speed sets wrist motor to desired speed given that it is within the encoder limits
"desired motor speed"

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +     * Using a PID command, elbow will rotate to a setpoint using the PID Controller. Will mainly be used in autonomous.
Remove "will mainly be used in autonomous"

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +     * @param setpoint the point desired to be reached by the elbow
"desired setpoint"

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +     * Using a PID command, wrist will rotate to a setpoint using the PID Controller. Will mainly be used in autonomous.
remove "will mainly be used in autonomous"

2023-02-22 22:50 UTC, kelmalon commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +     * @param setpoint the point desired to be reached by the wrist
"desired setpoint"

2023-02-24 22:38 UTC, kelmalon requested changes
Please add variables to store absolute encoder values, and update them in periodic. Please also put the values to SmartDashboard in periodic.

2023-02-25 23:35 UTC, kelmalon approved these changes
Looks good!

2023-02-27 23:11 UTC, DarkMG1 requested changes

2023-02-27 23:11 UTC, DarkMG1 commented on src/main/java/org/troyargonauts/subsystems/Arm.java
> +    public enum intakeState {
Please make this "IntakeState"

2023-03-02 23:10 UTC, DarkMG1 approved these changes

2023-03-03 01:32 UTC, akashsarada approved these changes
Looks good!

2023-03-03 01:33 UTC, merged