Subsystem/pneumatics
Troy-Argonauts/2023RobotCode pull request #8
Opened 2023-01-21 22:12 UTC by aarooshg

We wrote the code for our pneumatics for both the elevator and the manipulator. This included writing methods containing if-then loops to show the different states of the pneumatics of the manipulator and elevator and made it as simple as possible.

2023-01-21 22:25 UTC, akashsarada requested changes
Can we make the pneumatic states as enumerators rather than booleans?

2023-01-25 21:00 UTC, akashsarada approved these changes
Looks good!

2023-02-22 16:36 UTC, kelmalon requested changes
Please add Javadocs, and Remove Manipulator Solenoid. There are only pneumatic on the elevator now.

2023-02-24 22:30 UTC, kelmalon approved these changes
Looks good! Ready to merge.

2023-03-02 20:28 UTC, akashsarada requested changes

2023-03-02 20:28 UTC, akashsarada commented on src/main/java/org/troyargonauts/Constants.java
> +        int kElevatorForwardChannel = 0;
The constants need to be in the UPPER_CASE format, not in the Hungarian format.

2023-03-02 23:10 UTC, DarkMG1 approved these changes

2023-03-29 00:45 UTC, DarkMG1 commented
Unneeded and outdated.

2023-03-29 00:45 UTC, closed without merging